//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fina_Poll_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Fina_Poll_SystemEntities : DbContext
    {
        public Fina_Poll_SystemEntities()
            : base("name=Fina_Poll_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PollItems> PollItems { get; set; }
        public DbSet<PollItemTypes> PollItemTypes { get; set; }
        public DbSet<Polls> Polls { get; set; }
    }
}
