//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fina_Poll_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class PollItems : IEntity
    {
        public PollItems()
        {
            this.PollItemTypes = new HashSet<PollItemTypes>();
        }
    
        public int ID { get; set; }
        public int PollID { get; set; }
        public string Name { get; set; }
        public Nullable<int> OrderIndex { get; set; }
        public string Description { get; set; }
    
        public virtual Polls Polls { get; set; }
        public virtual ICollection<PollItemTypes> PollItemTypes { get; set; }
    }
}
