//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fina_Poll_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polls : IEntity
    {
        public Polls()
        {
            this.PollItems = new HashSet<PollItems>();
        }
    
        public int ID { get; set; }
        public System.DateTime TDate { get; set; }
        public Nullable<System.DateTime> WaitDays { get; set; }
        public string Version { get; set; }
    
        public virtual ICollection<PollItems> PollItems { get; set; }
    }
}
